### ISSUE TITLE
Website seems to be down: "403 Forbidden"

### ISSUE THREAD

**Issue by kylebeggs** [SimVascular/vascularmodel#8]
### Description

When navigating to [vascularmodel.com](vascularmodel.com), we are met with:

> Forbidden
> You don't have permission to access this resource.
> 
> Apache/2.4.29 (Ubuntu) Server at www.vascularmodel.com Port 443

### Reproduction

Go to [vascularmodel.com](vascularmodel.com)

### Expected behavior

to see the repo of models

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment]
The website has been redeployed and is up and running.
